image: docker:latest

stages:
    - build
    - test

docker build:
    stage: build
    before_script:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - docker-compose --version
    script:
        - docker-compose build    

composer install:
    stage: build
    before_script:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - docker-compose --version
    script:
        - composer install
        - docker-compose up --build
    cache:
        paths:
        - vendor/ 

cypress:
    stage: test
    before_script:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - docker-compose --version
    script:
        - docker-compose up --build
        - sleep 120
        - npm install
        - npm run cypress
    cache:
        paths:
            - vendor
            - node_modules/
