image: tiangolo/docker-with-compose

stages:
    - build
    - test

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build containers:
    stage: build
    script:
        - docker-compose build

composer install:
    stage: build
    script:
        - composer install
    cache:
        paths:
        - vendor/


cypress:
    stage: test
    script:
        - docker-compose up --build
        - sleep 120
        - npm install
        - npm run cypress
    cache:
        paths:
            - vendor
            - node_modules/
