image: tiangolo/docker-with-compose

stages:
    - build
    - test

before_script:
    - docker login -u msoenen -password-stdin 1c623a2a-919c-4df2-8a0c-fcf59863fd88

build containers:
    stage: build
    script:
        - docker-compose build

composer install:
    stage: build
    script:
        - composer install
    cache:
        paths:
        - vendor/
