image: tiangolo/docker-with-compose

services:
    - docker:dind

stages:
    - build
    - test

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build containers:
    stage: build
    script:
        - docker-compose build

composer install:
    stage: build
    script:
        - composer install
    cache:
        paths:
        - vendor/
