image: tiangolo/docker-with-compose

stages:
    - build
    - test

build containers:
    stage: build
    script:
        - docker-compose build

composer install:
    stage: build
    script:
        - composer install
    cache:
        paths:
        - vendor/
