stages:
    - build
    - test

docker build:
    stage: build
    image: tiangolo/docker-with-compose
    before_script:
        - docker-compose --version
    script:
        - docker-compose build    

composer install:
    stage: build
    image: tiangolo/docker-with-compose
    before_script:
        - docker-compose --version
    script:
        - composer install
        - docker-compose up --build
    cache:
        paths:
        - vendor/ 

cypress:
    stage: test
    image: tiangolo/docker-with-compose
    before_script:
        - docker-compose --version
    script:
        - docker-compose up --build
        - sleep 120
        - npm install
        - npm run cypress
    cache:
        paths:
            - vendor
            - node_modules/
